NYUTeamUp/NYUTeamUp/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^teamupapp/', include('teamupapp.urls')),
    url(r'^admin/', admin.site.urls),
]

NYUTeamUp/teamupapp/urls.py
from django.conf.urls import url

from . import views

app_name = 'teamupapp'
urlpatterns = [
    url(r'^$', views.LandingView.as_view(), name='index'),
    url(r'^(?P<userId>[a-zA-Z0-9]+)/myproj/$', views.myProjList, name='myProjList'),
    url(r'^(?P<userId>[a-zA-Z0-9]+)/myapps/$', views.myApplications, name='myApplications'),
    url(r'^(?P<category>[a-zA-Z]+)/list/$', views.projList, name='projList'),
    url(r'^(?P<projectId>[a-zA-Z0-9]+)/detail/$', views.projDetail, name='projDetail'),
]

NYUTeamUp/teamupapp/models.py
from django.db import models

class Login(models.Model):
	loginId = models.CharField(max_length=10)
	userName = models.CharField(max_length=25)
	password = models.CharField(max_length=25)

class User(models.Model):
	userId = models.CharField(max_length=25)
	loginId = models.ForeignKey(Login, on_delete=models.CASCADE)
	name = models.CharField(max_length=50)
	areaOfInterest=models.CharField(max_length=50)
	role = models.CharField(max_length=20)
	emailId = models.EmailField(max_length=50)
	resumeDoc = models.FileField(upload_to='NYUTeamUp/teamupapp/storage/',default='NYUTeamUp/teamupapp/storage/')

class Project(models.Model):
	projectId = models.CharField(max_length=25)
	projectName = models.CharField(max_length=50)
	userId = models.ForeignKey(User, on_delete=models.CASCADE)
	category = models.CharField(max_length=25)
	description = models.TextField()

class Job(models.Model):
	jobId = models.CharField(max_length=25)
	projectId = models.ForeignKey(Project, on_delete=models.CASCADE)
	jobName = models.CharField(max_length=50, default='')
	requirement = models.TextField()
	timeStamp = models.DateTimeField()
	numOfPositions = models.IntegerField()

class Application(models.Model):
	appId=models.CharField(max_length=25)
	jobId = models.ForeignKey(Job, on_delete=models.CASCADE)
	userId = models.ForeignKey(User, on_delete=models.CASCADE)

NYUTeamUp/teamupapp/views.py
from django.shortcuts import render
from django.views import generic
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse

from teamupapp.models import Login,User,Project,Job,Application

class LandingView(generic.ListView):
	template_name = 'teamupapp/index.html'
	context_object_name = 'category_list'

	def get_queryset(self):
		project_list =  Project.objects.all()
		category_list = []
		for project in  project_list:
			category_list.append(project.category)
		category_list = set(category_list)
		return category_list

class MyProjsView(generic.ListView):
	template_name = ''

class MyAppsView(generic.ListView):
	template_name = ''

def myApplications(request, userId):
	myAppsList = Application.objects.filter(userId=userId)
	return render(request, 'teamupapp/myapps.html', {'myAppslist': myAppsList})

def myProjList(request, userId):
	myProjList = Project.objects.filter(userId=userId)
	return render(request, 'teamupapp/myproj.html', {'mylist':myProjList})

def projDetail(request, projectId):
	project = Project.objects.filter(projectId=projectId)
	job_list = Job.objects.filter(projectId=projectId)
	#user = User.objects.filter(userId=project.userId)
	return render(request, 'teamupapp/detail.html', {'job_list':job_list})

def projList(request, category):
	project_list = Project.objects.filter(category=category)
	return render(request, 'teamupapp/list.html', {'project_list':project_list})

def loggedOut(request):
	return render(request, 'teamupapp/loggedout.html')

NYUTeamUp/NYUTeamUp/templates/TeamUpapp/home.html
{% extends 'base.html' %}

{% block title %}Login{% endblock %}

{% block content %}
  <h2>Home</h2>
{% endblock %}

NYUTeamUp/teamupapp/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head></head>

<body>
  <meta charset="utf-8">
  <title>{% block title %} NYU TeamUp {% endblock %}</title>
  <link rel="stylesheet" type="text/css" href="{% static 'projectStyle.css' %}">
  <script src="{%  static 'jquery-3.0.0.js'%}"></script>
  <script src="{%  static 'projectJS.js'%}"></script>
  <div id="head-container" class="head-container" style="display: block;"><div>TeamUp !</div></div>
  <div id="header-tile" class="header-tile">
    <a href="#">
        <div class="hover-tile">
            <div id="add-project" class="add-project head-tile">Add project</div>
        </div>
    </a>
    <a href="{% url 'teamupapp:myProjList' '12345' %}">
        <div class="hover-tile">
            <div id="my-projects" class="my-projects head-tile">My Projects</div>
        </div>
    </a>
    <a href="{% url 'teamupapp:myApplications' '12345' %}">
        <div class="hover-tile">
            <div id="my-applications" class="my-applications head-tile">My Applications</div>
        </div>
    </a>
    <a href="#">
        <div class="hover-tile">
            <div id="my-profile" class="my-profile head-tile">My Profile</div>
        </div>
    </a>
    <a href="#">
        <div class="hover-tile">
            <div id="logout" class="logout head-tile">Logout</div>
        </div>
    </a>
  </div>
  <main>
    {% block content %}
    {% endblock %}
  </main>
  <!--<footer id="page-foot" class="page-foot">
    <p>Copyright @HackNYU2017</p>
  </footer>-->
</body>
</html>

NYUTeamUp/teamupapp/templates/teamupapp/detail.html
{% extends 'base.html' %}
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'projectStyle.css' %}" />
{% block content %}

    <div><a href="#">{{ project.projectName }}</a>
        <p>{{ project.description }}</p>
        <p> Contact : {{ user.emailId }} hp107@nyu.edu</p>
    </div>
    {% if job_list %}
      {% for job in job_list %}
        <div>Requirements:{{ job.requirement }}
             <p>Number of positions: {{ job.numOfPositions }}</p>
             <div id="Apply-{{category}}-container" class="Apply-{{category}}-container Apply-container green-button" href="#">Apply
        </div>

      {% endfor %}
    {% else %}
      <p>No projects available</p>
    {% endif %}
{% endblock %}

NYUTeamUp/teamupapp/templates/teamupapp/index.html
{% extends 'base.html' %}

{% block content %}

    {% if category_list %}
      {% for category in category_list %}
          <a href="{% url 'teamupapp:projList' category%}">
            <div id="category-{{category}}-container" class="category-{{category}}-container category-container">
                <div>{{category}}</div>
            </div>
          </a>
      {% endfor %}
    {% else %}
      <p>No projects available</p>
    {% endif %}

{% endblock %}

NYUTeamUp/teamupapp/templates/teamupapp/list.html
{% extends 'base.html' %}
{% block content %}

    {% if project_list %}
      {% for project in project_list %}
        <a href="{% url 'teamupapp:projDetail' project.projectId %}">
            <div id="category-{{project}}-container" class="category-{{project}}-container project-container">
                <div>{{ project.projectName }}</div>
                <p>Description: {{ project.description }}</p>
            </div>
        </a>
      {% endfor %}
    {% else %}
      <p>No projects available</p>
    {% endif %}
{% endblock %}

NYUTeamUp/teamupapp/templates/teamupapp/loggedout.html
{% extends 'base.html' %}

{% block title %}Successfully logged out!{% endblock %}

{% block content %}
  <h2>Logged out</h2>
  <p>You have been successfully logged out.</p>
    <h1>See you Soon!</h1>
  <p><a href="{% url 'login' %}">Log in</a> again.</p>
{% endblock %}

NYUTeamUp/teamupapp/templates/teamupapp/login.html
{% extends 'base.html' %}

{% block title %}Login{% endblock %}

{% block content %}
  <h2>Login</h2>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Login</button>
  </form>
{% endblock %}

NYUTeamUp/teamupapp/templates/teamupapp/loogedout.html
{% extends 'base.html' %}

{% block title %}Successfully logged out!{% endblock %}

{% block content %}
  <h2>Logged out</h2>
  <p>You have been successfully logged out.</p>
  <p><a href="{% url 'login' %}">Log in</a> again.</p>
{% endblock %}

NYUTeamUp/teamupapp/templates/teamupapp/myapps.html
{% extends 'base.html' %}
{% block content %}

    {% if project_list %}
      {% for project in project_list %}
        <div><a href="{% url 'teamupapp:projDetail' project.projectId %}">{{ project.projectName }}</a>
             <p>{{ project.description }}</p>
        </div>
      {% endfor %}
    {% else %}
      <p>No projects available</p>
    {% endif %}
{% endblock %}

NYUTeamUp/teamupapp/templates/teamupapp/myproj.html
{% extends 'base.html' %}
{% block content %}

    {% if project_list %}
      {% for project in project_list %}
        <div><a href="{% url 'teamupapp:projDetail' project.projectId %}">{{ project.projectName }}</a>
             <p>{{ project.description }}</p>
        </div>
      {% endfor %}
    {% else %}
      <p>No projects available</p>
    {% endif %}
{% endblock %}